### ISSUE TITLE
Problem in Eye detection 

### ISSUE THREAD

**Issue by rsrinath14** [ankitwarbhe/ComputerVision#3]
You need to convert the image to gray scale  before passing it to the function.
Its also recommended to first detect the face and later detect eyes with the help of the cropped face, otherwise you'll have lot of false positives in the detection.

**Comment by ankitwarbhe** [comment]
Thank you for fixing the Issue Now I have got exactly what was wrong with the code previous I am merging the Request and closing the issue.
Kudos to You.
